# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: mufitorsion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test-env
        channels: conda-forge,defaults

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -c conda-forge ipopt tamkin
        pip install ruff pytest
        pip install .

    - name: Lint with ruff
      shell: bash -l {0}
      run: |
        python -m ruff check

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest -m "not slow"
